### ISSUE TITLE
SlidingPanel pushing content instead of overlaying

### ISSUE THREAD

**Issue by afarcilla** [cjdev/visual-stack#116]
When the SlidingPanel Redux component changes to an "active" state, it pushes all other content to side. For example, I have the ToggleIcon in my Header but once I click it to reveal the SlidingPanel, the Header and its contents resize. The desired behavior to would be similar to the non-redux SlidingPanel where the SlidingPanel is overlayed.

![image](https://user-images.githubusercontent.com/3254023/46232321-abe54080-c323-11e8-9370-cade37ee9d99.png)

**Comment by afarcilla** [comment]
@Nedda

**Comment by fiddlerwoaroof** [comment]
Verified that the PR fixes the issue.
