### ISSUE TITLE
In Sliding Panel page, text is truncated and there is no way to scroll

### ISSUE THREAD

**Issue by mirceaned** [cjdev/visual-stack#120]
On http://visual-stack-dev.s3-website-us-east-1.amazonaws.com/components/slidingpanel in Chrome, with scale at 100%, a long line of text is truncated and there is no way to scroll to the right, see screenshot. It’s not obvious that some of the text is not displayed, word wrap or ability to scroll would be helpful.

**Comment by mirceaned** [comment]
![screen shot 2018-10-15 at 10 15 03 am](https://user-images.githubusercontent.com/7275725/46967645-055ca780-d066-11e8-81b8-e215d0f6cfe8.png)

**Comment by nicolasfont** [comment]
No longer an issue
