### ISSUE TITLE
Un-pin Node Version 

### ISSUE THREAD

**Issue by Nedda** [cjdev/visual-stack#161]
In the PR for the React 16 upgrade, node had to be pinned to 11.10.1 in Travis due to a jest issue: 
https://github.com/facebook/jest/issues/8069
Be sure to unpin in travis for the visual stack docs deployment as well! 
https://github.com/cjdev/visual-stack/pull/164/ 

Once this issue is resolved, we'll upgrade our jest issue and un-pin node in our travis config.

**Comment by HuoShengdi** [comment]
Waiting on releases from:
https://github.com/nodejs/node
https://github.com/facebook/create-react-app
