### ISSUE TITLE
Specifically name spaces visual stack css

### ISSUE THREAD

**Issue by Nedda** [cjdev/visual-stack#95]
To prevent name-space collisions with other applications that use visual stack, it would be best to update our css to be name-spaced. 
Adding a 'vs-' before css classes should be sufficient.

**Comment by fhwrdh** [comment]
Will we have to treat this as a breaking change? Users of previous versions may have used the old class names to add/override styles?

**Comment by namini67** [comment]
Sure, that is a possibility. We can bump the version if this is implemented. Should I create a tag for breaking changes?

**Comment by fhwrdh** [comment]
Nah, just didn't want to lose track of the thought.

**Comment by Nedda** [comment]
Fixed in the above PR's
